import { readFileSync } from "node:fs";
import { createHash } from "node:crypto";
import path from "node:path";
import os from "node:os";
import * as rt from "@midnight-ntwrk/compact-runtime";
import { prove, type KeyMaterialProvider } from "@midnight-ntwrk/zkir-v2";
// Compiled Compact contract output (see contracts/eligibility.compact).
// Regenerated by `compact compile` — not hand-written, do not edit.
import { Contract } from "../../../contracts/managed/eligibility/contract/index.js";

/**
 * Server-only real ZK proving for the `verifyAndApply` circuit.
 *
 * This runs the exact compiled contract module through
 * `@midnight-ntwrk/compact-runtime` (the same execution engine that would
 * run on-chain) to get real proof data, then hands that to
 * `@midnight-ntwrk/zkir-v2`'s `prove()` to produce an actual PLONK proof
 * using the circuit's real prover/verifier keys and the Compact compiler's
 * BLS trusted-setup parameters.
 *
 * This does NOT talk to the Dockerized proof server over HTTP — the public
 * Midnight SDK only exposes proof-server HTTP proving via
 * `@midnight-ntwrk/midnight-js-contracts`' `createUnprovenCallTx`, which
 * requires a deployed/found contract handle, which in turn requires a full
 * wallet + indexer + node pipeline (out of scope here). `zkir-v2`'s
 * `prove()` runs the same class of PLONK computation locally instead,
 * using the identical circuit artifacts — a genuine, standalone proof,
 * just not routed through the container's HTTP API.
 *
 * Never import this module from client ("use client") code — it touches
 * Node's filesystem and loads native WASM.
 */

const PROJECT_ROOT = process.cwd();
const CONTRACT_DIR = path.join(PROJECT_ROOT, "contracts", "managed", "eligibility");

// Candidate directories for the Compact compiler's BLS trusted-setup
// parameter cache (`bls_midnight_2p<k>`). Tries a project-local copy first
// (see .zk-params/, gitignored — copy it from the machine's Compact CLI
// cache), then falls back to the CLI's own cache location so this also
// works unmodified on a machine where `compact compile` has already run.
const PARAMS_DIR_CANDIDATES = [
  path.join(PROJECT_ROOT, ".zk-params"),
  path.join(os.homedir(), ".cache", "midnight", "zk-params"),
];

function readFirstExisting(candidatePaths: string[]): Buffer {
  const errors: string[] = [];
  for (const candidate of candidatePaths) {
    try {
      return readFileSync(candidate);
    } catch (err) {
      errors.push(`${candidate}: ${err instanceof Error ? err.message : String(err)}`);
    }
  }
  throw new Error(`Could not find required file in any candidate path:\n${errors.join("\n")}`);
}

const keyProvider: KeyMaterialProvider = {
  async lookupKey(keyLocation: string) {
    return {
      proverKey: readFileSync(path.join(CONTRACT_DIR, "keys", `${keyLocation}.prover`)),
      verifierKey: readFileSync(path.join(CONTRACT_DIR, "keys", `${keyLocation}.verifier`)),
      ir: readFileSync(path.join(CONTRACT_DIR, "zkir", `${keyLocation}.bzkir`)),
    };
  },
  async getParams(k: number) {
    return readFirstExisting(PARAMS_DIR_CANDIDATES.map((dir) => path.join(dir, `bls_midnight_2p${k}`)));
  },
};

// --- Attestation hashing -----------------------------------------------
//
// Mirrors contracts/eligibility.compact's:
//   persistentHash<[Bytes<32>, Uint<8>, Boolean]>([issuerPublicKey, matchScore, meetsMinCriteria])
// (see `_descriptor_4` / `_persistentHash_0` in the compiled contract).

const descBytes32 = new rt.CompactTypeBytes(32);
const descUint8 = new rt.CompactTypeUnsignedInteger(255n, 1);
const descBool = rt.CompactTypeBoolean;

type AttestationTuple = [Uint8Array, bigint, boolean];

const attestationTupleType: rt.CompactType<AttestationTuple> = {
  alignment: () => descBytes32.alignment().concat(descUint8.alignment().concat(descBool.alignment())),
  toValue: (v) => descBytes32.toValue(v[0]).concat(descUint8.toValue(v[1]).concat(descBool.toValue(v[2]))),
  fromValue: (v) => [descBytes32.fromValue(v), descUint8.fromValue(v), descBool.fromValue(v)],
};

/**
 * `ISSUER_PUBLIC_KEY` in src/lib/issuer.ts is a fixed demo constant chosen
 * to spell "fa1rh1re" — which is NOT valid 32-byte hex (`r`/`h`/`i` aren't
 * hex digits, and it's one byte short). The circuit requires a real
 * `Bytes<32>` value, so this derives a stable 32-byte value from it
 * deterministically (SHA-256 of the literal string) instead of truncating
 * on the invalid hex a plain decode would produce. Used consistently for
 * every server-side use of this key, so the attestation signature and the
 * circuit call always agree on the same bytes. Falls through to a real hex
 * decode first, so a well-formed 32-byte hex key (e.g. a future non-demo
 * issuer key) is used as-is.
 */
export function canonicalPublicKeyBytes(rawKey: string): Uint8Array {
  if (/^[0-9a-fA-F]{64}$/.test(rawKey)) {
    return rt.fromHex(rawKey);
  }
  return new Uint8Array(createHash("sha256").update(rawKey, "utf8").digest());
}

export function computeAttestationSignature(
  issuerPublicKey: Uint8Array,
  matchScore: bigint,
  meetsMinCriteria: boolean,
): Uint8Array {
  return rt.persistentHash(attestationTupleType, [issuerPublicKey, matchScore, meetsMinCriteria]);
}

// --- Circuit execution + real PLONK proof generation --------------------

const contract = new Contract({});
// Demo-only fixed coin key: no real wallet/coin is involved in local proving.
const COIN_PUBLIC_KEY: rt.EncodedCoinPublicKey = { bytes: new Uint8Array(32) };

// In-memory ledger state, persisted across requests within this server
// process (resets on server restart — there is no real chain/indexer
// behind this demo). This lets the real circuit's own nullifier-replay
// assertion and `qualifiesCount` increment behave correctly across
// multiple proof requests, exactly as the compiled contract defines them.
let ledgerState: rt.ChargedState | undefined;

async function getLedgerState(): Promise<rt.ChargedState> {
  if (!ledgerState) {
    const init = await contract.initialState({
      initialZswapLocalState: rt.emptyZswapLocalState(COIN_PUBLIC_KEY),
      initialPrivateState: {},
    });
    ledgerState = init.currentContractState.data;
  }
  return ledgerState;
}

export interface RealProofInput {
  matchScore: bigint;
  meetsMinCriteria: boolean;
  candidateSecret: Uint8Array;
  issuerPublicKey: Uint8Array;
  issuerSignature: Uint8Array;
  jobId: Uint8Array;
  minScoreThreshold: bigint;
  expiryTimestamp: bigint;
}

export interface RealProofOutput {
  nullifier: Uint8Array;
  qualifies: boolean;
  zkProof: Uint8Array;
  proveTimeMs: number;
}

const nullifierType = new rt.CompactTypeVector(2, new rt.CompactTypeBytes(32));

/**
 * Executes the real compiled `verifyAndApply` circuit against real witness
 * values and generates a real PLONK proof for the resulting transcript.
 * Throws if the circuit's own assertions fail (invalid attestation, or a
 * replayed nullifier) — callers should treat any throw as "could not prove"
 * and fall back accordingly.
 */
export async function generateRealProof(input: RealProofInput): Promise<RealProofOutput> {
  const state = await getLedgerState();
  const context = rt.createCircuitContext(rt.dummyContractAddress(), COIN_PUBLIC_KEY, state, {});

  const callResult = await contract.circuits.verifyAndApply(
    context,
    input.matchScore,
    input.meetsMinCriteria,
    input.candidateSecret,
    input.issuerPublicKey,
    input.issuerSignature,
    input.jobId,
    input.minScoreThreshold,
    input.expiryTimestamp,
  );

  // Circuit execution succeeded (all `assert`s passed) — commit the updated
  // ledger state so the nullifier is genuinely marked used for next time.
  ledgerState = new rt.ChargedState(callResult.context.currentQueryContext.state.state);

  const proofData = callResult.proofData;

  const nullifier = rt.persistentHash(nullifierType, [input.candidateSecret, input.jobId]);
  const qualifies = input.matchScore >= input.minScoreThreshold && input.meetsMinCriteria;

  const serializedPreimage = rt.proofDataIntoSerializedPreimage(
    proofData.input,
    proofData.output,
    proofData.publicTranscript,
    proofData.privateTranscriptOutputs,
    "verifyAndApply",
  );

  const t0 = Date.now();
  const zkProof = await prove(serializedPreimage, keyProvider);
  const proveTimeMs = Date.now() - t0;

  return { nullifier, qualifies, zkProof, proveTimeMs };
}
