// WebSocket polyfill must be installed before any SDK import touches the
// indexer/node GraphQL-over-WS clients (same requirement as
// wallet-setup/src/index.ts and scripts/deploy-contract.ts).
import { WebSocket } from "ws";
// @ts-expect-error WebSocket polyfill for apollo/graphql-ws client
globalThis.WebSocket = WebSocket;

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import * as Rx from "rxjs";

import { setNetworkId, getNetworkId } from "@midnight-ntwrk/midnight-js-network-id";
import * as ledger from "@midnight-ntwrk/midnight-js-protocol/ledger";
import { CompiledContract } from "@midnight-ntwrk/midnight-js-protocol/compact-js";
import { deployContract } from "@midnight-ntwrk/midnight-js-contracts";
import { indexerPublicDataProvider } from "@midnight-ntwrk/midnight-js-indexer-public-data-provider";
import { httpClientProofProvider } from "@midnight-ntwrk/midnight-js-http-client-proof-provider";
import { levelPrivateStateProvider } from "@midnight-ntwrk/midnight-js-level-private-state-provider";
import { NodeZkConfigProvider } from "@midnight-ntwrk/midnight-js-node-zk-config-provider";
import type { MidnightProvider, WalletProvider } from "@midnight-ntwrk/midnight-js-types";

import {
  HDWallet,
  Roles,
  createKeystore,
  WalletFacade,
  ShieldedWallet,
  UnshieldedWallet,
  DustWallet,
  NoOpTransactionHistoryStorage,
  PublicKey,
  type DefaultConfiguration,
} from "@midnightntwrk/wallet-sdk";

// Compiled Compact contract output (see contracts/eligibility.compact).
// Regenerated by `compact compile` — not hand-written, do not edit.
import { Contract } from "../contracts/managed/eligibility/contract/index.js";

/**
 * Deploys the compiled `eligibility` contract to Midnight Preprod, waiting
 * out DUST sync in a SINGLE long-lived wallet connection instead of the
 * "retry deploy-contract.ts every 15 minutes" approach this replaces.
 *
 * Why this exists: scripts/deploy-contract.ts opens a fresh WalletFacade,
 * waits only for the unshielded sub-wallet, then immediately tries to
 * deploy — which needs the DUST sub-wallet to balance the transaction fee.
 * On Preprod a fresh wallet's dust sync takes ~2h, and dust sync progress
 * is NOT persisted to disk between processes (.dapp-state/ only holds
 * contract private state, not wallet chain-sync position) — WalletFacade
 * always resumes from a low index in a new process. A poll loop that
 * restarts deploy-contract.ts on an interval therefore re-opens the
 * connection and restarts dust sync from ~0% every time, never actually
 * accumulating enough sync progress to see spendable DUST coins.
 *
 * This script instead opens ONE WalletFacade and keeps it alive for the
 * whole run: dust sync keeps progressing in the background across every
 * check and every deploy attempt, because the connection is never torn
 * down. It polls dust status cheaply and only invokes the real
 * (expensive, proves+balances+submits) deployContract() call once the
 * dust sub-wallet has actually observed a spendable coin.
 *
 * Usage:
 *   npx tsx scripts/deploy-when-ready.ts
 *
 * On success, writes the deployed contract's address (and deployment
 * metadata) to config/deployed-contracts.json — same shape/location as
 * scripts/deploy-contract.ts.
 */

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const PROJECT_ROOT = path.resolve(__dirname, "..");
const CONTRACT_NAME = "eligibility";
const CONTRACT_DIR = path.join(PROJECT_ROOT, "contracts", "managed", CONTRACT_NAME);
const WALLET_SETUP_ENV_PATH = path.resolve(PROJECT_ROOT, "..", "wallet-setup", ".env");
const DEPLOYED_CONTRACTS_PATH = path.join(PROJECT_ROOT, "config", "deployed-contracts.json");
const PRIVATE_STATE_DIR = path.join(PROJECT_ROOT, ".dapp-state", "private-state");

const PROOF_SERVER_URL = "http://localhost:6300";

// Preprod endpoints — identical to wallet-setup/src/index.ts and
// scripts/deploy-contract.ts (verified live via curl before writing those).
const PREPROD = {
  indexerHttpUrl: "https://indexer.preprod.midnight.network/api/v4/graphql",
  indexerWsUrl: "wss://indexer.preprod.midnight.network/api/v4/graphql/ws",
  relayURL: "wss://rpc.preprod.midnight.network",
};

setNetworkId("preprod");

// How long this process is willing to keep the wallet connected and
// syncing before giving up. ~2h was the observed full dust-sync time for a
// fresh Preprod wallet; this gives real margin on top of that.
const MAX_RUNTIME_MS = 3 * 60 * 60 * 1000;
// Cheap "has anything changed" check — no proving, no network write.
const DUST_POLL_INTERVAL_MS = 15_000;
// Real deploy attempts prove+balance+submit a transaction — expensive, so
// these are spaced out even once dust coins are observed (a single coin
// observed doesn't guarantee it's enough to cover the fee yet).
const DEPLOY_ATTEMPT_INTERVAL_MS = 2 * 60 * 1000;
// Heartbeat so a long silent stretch is still visibly "alive" in the log.
const STATUS_LOG_INTERVAL_MS = 60_000;
// Ceiling on each individual facade.state() read inside the poll loop. Without
// this, a stalled/dropped connection makes that single await hang for the
// rest of MAX_RUNTIME_MS instead of the loop actually cycling every
// DUST_POLL_INTERVAL_MS as intended — observed in practice: a run's dust
// sync progressed healthily (~193 idx/s) for ~1h26m, then the connection
// silently stalled and the loop never polled again until the outer timeout
// finally fired ~1.5h later. This timeout turns that stall into a logged,
// recoverable retry instead of a silent hang.
const STATE_POLL_TIMEOUT_MS = 30_000;
// How long to wait, per check cycle, for facade.waitForSyncedState() (which
// waits on shielded + unshielded + dust together) to resolve before giving
// up on this cycle and re-checking later. Bounded so a single stalled
// connection can't block the loop from ever logging a heartbeat again.
const WAIT_FOR_SYNCED_STATE_TIMEOUT_MS = 5 * 60_000;

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

/** Races a promise against a timeout so a hanging SDK call fails loudly instead of silently. */
function withTimeout<T>(promise: Promise<T>, ms: number, label: string): Promise<T> {
  return Promise.race([
    promise,
    new Promise<never>((_, reject) => {
      const t = setTimeout(
        () => reject(new Error(`[timeout] ${label} did not resolve within ${ms / 1000}s`)),
        ms,
      );
      t.unref();
    }),
  ]);
}

function loadWalletSeed(): string {
  if (!existsSync(WALLET_SETUP_ENV_PATH)) {
    throw new Error(
      `Could not find ${WALLET_SETUP_ENV_PATH}. This script reads the funded wallet's seed ` +
        "from the sibling wallet-setup project (read-only) — make sure that project exists " +
        "and has already generated a wallet (WALLET_SEED in its .env).",
    );
  }
  const content = readFileSync(WALLET_SETUP_ENV_PATH, "utf8");
  const match = content.match(/^WALLET_SEED=(.+)$/m);
  if (!match || match[1].trim().length === 0) {
    throw new Error(`WALLET_SEED not found in ${WALLET_SETUP_ENV_PATH}.`);
  }
  return match[1].trim();
}

function deriveKeys(seedHex: string) {
  const hd = HDWallet.fromSeed(Buffer.from(seedHex, "hex"));
  if (hd.type !== "seedOk") {
    throw new Error("Invalid wallet seed");
  }
  const result = hd.hdWallet
    .selectAccount(0)
    .selectRoles([Roles.Zswap, Roles.NightExternal, Roles.Dust])
    .deriveKeysAt(0);
  hd.hdWallet.clear();
  if (result.type !== "keysDerived") {
    throw new Error(`Key derivation failed: ${result.type}`);
  }
  return result.keys;
}

/** See wallet-setup/src/index.ts for the detailed rationale on this readiness check. */
function isSubWalletReady(progress: {
  isConnected: boolean;
  appliedIndex: unknown;
  highestRelevantWalletIndex: unknown;
  isStrictlyComplete(): boolean;
}): boolean {
  if (typeof progress.appliedIndex !== "bigint" || typeof progress.highestRelevantWalletIndex !== "bigint") {
    return progress.isConnected === true;
  }
  try {
    return progress.isStrictlyComplete();
  } catch {
    return progress.isConnected === true;
  }
}

/** Waits for the unshielded sub-wallet to sync (does not wait on dust). */
async function connectUnshielded(wallet: WalletFacade, connectTimeoutMs: number) {
  return new Promise<Awaited<ReturnType<typeof wallet.waitForSyncedState>>>((resolve, reject) => {
    let connectTimer: NodeJS.Timeout | null = setTimeout(() => {
      sub.unsubscribe();
      reject(
        new Error(
          `[sync] Timed out after ${connectTimeoutMs / 1000}s: unshielded never reported isConnected=true.`,
        ),
      );
    }, connectTimeoutMs);

    const sub = wallet
      .state()
      .pipe(Rx.throttleTime(5_000, undefined, { leading: true, trailing: true }))
      .subscribe({
        next: (s) => {
          const u = s.unshielded.progress;
          const uReady = isSubWalletReady(u);
          console.log(`[sync] unshielded conn=${u.isConnected} ready=${uReady} ${u.appliedIndex}/${u.highestRelevantWalletIndex}`);
          if (connectTimer && u.isConnected) {
            clearTimeout(connectTimer);
            connectTimer = null;
          }
          if (uReady) {
            sub.unsubscribe();
            if (connectTimer) clearTimeout(connectTimer);
            resolve(s);
          }
        },
        error: (err) => {
          if (connectTimer) clearTimeout(connectTimer);
          reject(err);
        },
      });
  });
}

/**
 * Bridges a synced WalletFacade into the WalletProvider + MidnightProvider
 * shape midnight-js-contracts expects. balanceTx/submitTx delegate to the
 * live facade, not a stale snapshot, so this is safe to build once and
 * reuse across many deploy attempts as dust sync keeps progressing.
 */
function createWalletProvider(
  facade: WalletFacade,
  shieldedSecretKeys: ledger.ZswapSecretKeys,
  dustSecretKey: ledger.DustSecretKey,
  state: Awaited<ReturnType<typeof connectUnshielded>>,
): WalletProvider & MidnightProvider {
  return {
    getCoinPublicKey: () => state.shielded.coinPublicKey.toHexString(),
    getEncryptionPublicKey: () => state.shielded.encryptionPublicKey.toHexString(),
    async balanceTx(tx, ttl) {
      const recipe = await facade.balanceUnboundTransaction(
        tx,
        { shieldedSecretKeys, dustSecretKey },
        { ttl: ttl ?? new Date(Date.now() + 30 * 60 * 1000) },
      );
      return await facade.finalizeRecipe(recipe);
    },
    submitTx: (tx) => facade.submitTransaction(tx),
  } as WalletProvider & MidnightProvider;
}

function writeDeployedContractsFile(contractAddress: string, txId: string, blockHeight: unknown, unshieldedAddress: string) {
  const existing = existsSync(DEPLOYED_CONTRACTS_PATH)
    ? (JSON.parse(readFileSync(DEPLOYED_CONTRACTS_PATH, "utf8")) as Record<string, unknown>)
    : {};
  const updated = {
    ...existing,
    [CONTRACT_NAME]: {
      address: contractAddress,
      network: "preprod",
      txId,
      blockHeight: typeof blockHeight === "bigint" ? blockHeight.toString() : blockHeight,
      deployerUnshieldedAddress: unshieldedAddress,
      deployedAt: new Date().toISOString(),
    },
  };
  writeFileSync(DEPLOYED_CONTRACTS_PATH, JSON.stringify(updated, null, 2) + "\n", "utf8");
  console.log(`\nWrote deployment metadata to ${DEPLOYED_CONTRACTS_PATH}`);
}

async function main() {
  console.log("=".repeat(70));
  console.log(`Deploying '${CONTRACT_NAME}' to Midnight Preprod (long-lived, waits out DUST sync)`);
  console.log("=".repeat(70));

  const seedHex = loadWalletSeed();
  const keys = deriveKeys(seedHex);
  const networkId = getNetworkId();
  const unshieldedKeystore = createKeystore(keys[Roles.NightExternal], networkId);
  const unshieldedAddress = unshieldedKeystore.getBech32Address().toString();

  console.log(`Network:            ${networkId}`);
  console.log(`Unshielded address: ${unshieldedAddress}\n`);

  const health = await fetch(`${PROOF_SERVER_URL}/health`, { signal: AbortSignal.timeout(2000) }).catch(() => null);
  if (!health || !health.ok) {
    throw new Error(
      `Proof server not detected at ${PROOF_SERVER_URL}/health. Start it first ` +
        "(`docker compose up -d` from the FairHire project root) and re-run.",
    );
  }
  console.log(`Proof server detected at ${PROOF_SERVER_URL}.\n`);

  const shieldedSecretKeys = ledger.ZswapSecretKeys.fromSeed(keys[Roles.Zswap]);
  const dustSecretKey = ledger.DustSecretKey.fromSeed(keys[Roles.Dust]);

  const configuration: DefaultConfiguration = {
    networkId,
    indexerClientConnection: {
      indexerHttpUrl: PREPROD.indexerHttpUrl,
      indexerWsUrl: PREPROD.indexerWsUrl,
    },
    relayURL: new URL(PREPROD.relayURL),
    provingServerUrl: new URL(PROOF_SERVER_URL),
    costParameters: { feeBlocksMargin: 5 },
    txHistoryStorage: new NoOpTransactionHistoryStorage(),
  };

  console.log("[init] Building WalletFacade (this is the ONLY connection opened this run)...");
  const facade = await WalletFacade.init({
    configuration,
    shielded: (cfg) => ShieldedWallet(cfg).startWithSecretKeys(shieldedSecretKeys),
    unshielded: (cfg) => UnshieldedWallet(cfg).startWithPublicKey(PublicKey.fromKeyStore(unshieldedKeystore)),
    dust: (cfg) =>
      DustWallet(cfg).startWithSecretKey(dustSecretKey, ledger.LedgerParameters.initialParameters().dust),
  });
  console.log("[init] WalletFacade built. Starting sub-wallets...");
  await facade.start(shieldedSecretKeys, dustSecretKey);
  console.log("[init] Sub-wallets started. This connection stays open until success, a fatal error, or timeout.\n");

  try {
    console.log("[sync] Waiting for unshielded sync (connect timeout 60s)...");
    const state = await connectUnshielded(facade, 60_000);
    console.log("[sync] unshielded ready.\n");

    const nightBalance = state.unshielded.balances[ledger.unshieldedToken().raw] ?? 0n;
    console.log(`[balance] tNIGHT balance: ${nightBalance}`);
    if (nightBalance === 0n && state.unshielded.availableCoins.length === 0) {
      throw new Error(`No tNIGHT at ${unshieldedAddress}. Fund it first (see wallet-setup project) and re-run.`);
    }

    const walletProvider = createWalletProvider(facade, shieldedSecretKeys, dustSecretKey, state);

    if (!existsSync(PRIVATE_STATE_DIR)) {
      mkdirSync(PRIVATE_STATE_DIR, { recursive: true });
    }

    const zkConfigProvider = new NodeZkConfigProvider<"verifyAndApply">(CONTRACT_DIR);
    const providers = {
      privateStateProvider: levelPrivateStateProvider({
        privateStateStoreName: path.join(PRIVATE_STATE_DIR, `${CONTRACT_NAME}-private-state`),
        signingKeyStoreName: path.join(PRIVATE_STATE_DIR, `${CONTRACT_NAME}-signing-keys`),
        // Must satisfy the private-state store's complexity check (>=3 of
        // uppercase/lowercase/digit/special) — local-only storage, not a
        // real secret, but the string still has to pass that check.
        privateStoragePasswordProvider: () => "FairHire-Deploy-Local-Only-9x!",
        accountId: unshieldedAddress,
      }),
      publicDataProvider: indexerPublicDataProvider(PREPROD.indexerHttpUrl, PREPROD.indexerWsUrl),
      zkConfigProvider,
      proofProvider: httpClientProofProvider(PROOF_SERVER_URL, zkConfigProvider),
      walletProvider,
      midnightProvider: walletProvider,
    };

    const compiledContract = CompiledContract.make(CONTRACT_NAME, Contract).pipe(
      CompiledContract.withVacantWitnesses,
      CompiledContract.withCompiledFileAssets(CONTRACT_DIR),
    );

    console.log(
      `[wait] Polling dust status every ${DUST_POLL_INTERVAL_MS / 1000}s; will attempt deploy every ` +
        `${DEPLOY_ATTEMPT_INTERVAL_MS / 1000}s once a spendable DUST coin is observed. Ceiling: ` +
        `${MAX_RUNTIME_MS / 3_600_000}h.\n`,
    );

    const startedAt = Date.now();
    let lastStatusLogAt = 0;
    let lastDeployAttemptAt = 0;
    let consecutiveUnexpected = 0;
    let lastUnexpectedMsg = "";

    while (Date.now() - startedAt < MAX_RUNTIME_MS) {
      let liveState: Awaited<ReturnType<typeof connectUnshielded>>;
      try {
        liveState = await withTimeout(
          Rx.firstValueFrom(facade.state()),
          STATE_POLL_TIMEOUT_MS,
          "facade.state() poll",
        );
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        console.log(
          `[status] state poll stalled or errored (${msg}) — connection may have hiccuped; ` +
            `retrying in ${DUST_POLL_INTERVAL_MS / 1000}s without tearing down the wallet connection.`,
        );
        await sleep(DUST_POLL_INTERVAL_MS);
        continue;
      }

      const d = liveState.dust.progress;
      const dustBalance = liveState.dust.balance(new Date());
      const dustCoins = liveState.dust.availableCoins.length;

      if (Date.now() - lastStatusLogAt > STATUS_LOG_INTERVAL_MS) {
        console.log(
          `[status] ${new Date().toISOString()} dust sync ${String(d.appliedIndex)}/${String(d.highestRelevantWalletIndex)} ` +
            `conn=${d.isConnected} | dust balance=${dustBalance.toString()} availableCoins=${dustCoins}`,
        );
        lastStatusLogAt = Date.now();
      }

      const readyToCheckDeploy = dustCoins > 0 && Date.now() - lastDeployAttemptAt > DEPLOY_ATTEMPT_INTERVAL_MS;
      if (!readyToCheckDeploy) {
        await sleep(DUST_POLL_INTERVAL_MS);
        continue;
      }

      lastDeployAttemptAt = Date.now();

      // dustCoins > 0 is a cheap heuristic ("a coin exists somewhere in what
      // we've synced so far"), not proof the wallet's DUST state is fully
      // caught up to the chain tip — the previous attempt hit
      // InvalidDustSpendProof (error 170) exactly when dust sync was at
      // 99.86%, not 100%. facade.waitForSyncedState() is the SDK's own
      // authoritative signal (waits on shielded + unshielded + dust
      // together), so use it as a hard gate before spending a real
      // deployContract() attempt on a possibly-stale DUST spend proof.
      console.log(
        `[deploy] ${dustCoins} spendable DUST coin(s) observed — confirming full sync via ` +
          `waitForSyncedState() before attempting deployment...`,
      );
      try {
        await withTimeout(facade.waitForSyncedState(), WAIT_FOR_SYNCED_STATE_TIMEOUT_MS, "waitForSyncedState()");
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        console.log(
          `[deploy] not fully synced yet (${msg}) — a coin is visible but the wallet isn't caught up ` +
            `to the tip. Will re-check in ${DEPLOY_ATTEMPT_INTERVAL_MS / 1000}s without attempting a proof.`,
        );
        continue;
      }
      console.log("[deploy] Fully synced (shielded + unshielded + dust) — attempting deployment...");
      try {
        const deployed = await withTimeout(
          deployContract(providers as never, {
            compiledContract,
            privateStateId: `${CONTRACT_NAME}PrivateState`,
            initialPrivateState: {},
          } as never),
          180_000,
          "deployContract",
        );

        const { contractAddress, txId, blockHeight } = deployed.deployTxData.public;
        console.log("\n" + "=".repeat(70));
        console.log("Deployment succeeded.");
        console.log(`  contractAddress: ${contractAddress}`);
        console.log(`  txId:            ${txId}`);
        console.log(`  blockHeight:     ${blockHeight}`);
        console.log("=".repeat(70));

        writeDeployedContractsFile(contractAddress, txId, blockHeight, unshieldedAddress);
        return;
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        if (/InsufficientFunds|could not balance dust/i.test(msg)) {
          console.log(
            `[deploy] still insufficient dust despite ${dustCoins} coin(s) observed — dust sync keeps ` +
              `running in the background (connection stays open); retrying in ${DEPLOY_ATTEMPT_INTERVAL_MS / 1000}s.`,
          );
          consecutiveUnexpected = 0;
        } else {
          consecutiveUnexpected = msg === lastUnexpectedMsg ? consecutiveUnexpected + 1 : 1;
          lastUnexpectedMsg = msg;
          console.log(`[deploy] unexpected error (${consecutiveUnexpected}x in a row): ${msg}`);
          if (consecutiveUnexpected >= 3) {
            throw new Error(`Stopping: same unexpected error 3x in a row, likely not transient — ${msg}`);
          }
        }
      }
    }

    throw new Error(
      `Timed out after ${MAX_RUNTIME_MS / 3_600_000}h without a successful deploy — dust sync never ` +
        "produced a spendable coin in this connection's lifetime.",
    );
  } finally {
    await facade.stop();
  }
}

main()
  .catch((err) => {
    console.error("\nFatal error:", err);
    process.exitCode = 1;
  })
  .finally(() => {
    setTimeout(() => process.exit(process.exitCode ?? 0), 500).unref();
  });
