// WebSocket polyfill must be installed before any SDK import touches the
// indexer/node GraphQL-over-WS clients (same requirement as
// wallet-setup/src/index.ts).
import { WebSocket } from "ws";
// @ts-expect-error WebSocket polyfill for apollo/graphql-ws client
globalThis.WebSocket = WebSocket;

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import * as Rx from "rxjs";

import { setNetworkId, getNetworkId } from "@midnight-ntwrk/midnight-js-network-id";
import * as ledger from "@midnight-ntwrk/midnight-js-protocol/ledger";
import { CompiledContract } from "@midnight-ntwrk/midnight-js-protocol/compact-js";
import { deployContract } from "@midnight-ntwrk/midnight-js-contracts";
import { indexerPublicDataProvider } from "@midnight-ntwrk/midnight-js-indexer-public-data-provider";
import { httpClientProofProvider } from "@midnight-ntwrk/midnight-js-http-client-proof-provider";
import { levelPrivateStateProvider } from "@midnight-ntwrk/midnight-js-level-private-state-provider";
import { NodeZkConfigProvider } from "@midnight-ntwrk/midnight-js-node-zk-config-provider";
import type { MidnightProvider, WalletProvider } from "@midnight-ntwrk/midnight-js-types";

import {
  HDWallet,
  Roles,
  createKeystore,
  WalletFacade,
  ShieldedWallet,
  UnshieldedWallet,
  DustWallet,
  NoOpTransactionHistoryStorage,
  PublicKey,
  type DefaultConfiguration,
} from "@midnightntwrk/wallet-sdk";

// Compiled Compact contract output (see contracts/eligibility.compact).
// Regenerated by `compact compile` — not hand-written, do not edit.
import { Contract } from "../contracts/managed/eligibility/contract/index.js";

/**
 * Deploys the compiled `eligibility` contract to Midnight Preprod, signed
 * by the funded wallet in the sibling `wallet-setup` project (read-only —
 * this script never writes to wallet-setup/.env, it only reads
 * WALLET_SEED out of it).
 *
 * Usage:
 *   npx tsx scripts/deploy-contract.ts
 *
 * On success, writes the deployed contract's address (and deployment
 * metadata) to config/deployed-contracts.json, keyed by contract name, so
 * that a later API route can load it at runtime without hardcoding it
 * into source.
 */

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const PROJECT_ROOT = path.resolve(__dirname, "..");
const CONTRACT_NAME = "eligibility";
const CONTRACT_DIR = path.join(PROJECT_ROOT, "contracts", "managed", CONTRACT_NAME);
const WALLET_SETUP_ENV_PATH = path.resolve(PROJECT_ROOT, "..", "wallet-setup", ".env");
const DEPLOYED_CONTRACTS_PATH = path.join(PROJECT_ROOT, "config", "deployed-contracts.json");
const PRIVATE_STATE_DIR = path.join(PROJECT_ROOT, ".dapp-state", "private-state");

const PROOF_SERVER_URL = "http://localhost:6300";

// Preprod endpoints — identical to wallet-setup/src/index.ts (verified live
// via curl before writing that script).
const PREPROD = {
  indexerHttpUrl: "https://indexer.preprod.midnight.network/api/v4/graphql",
  indexerWsUrl: "wss://indexer.preprod.midnight.network/api/v4/graphql/ws",
  relayURL: "wss://rpc.preprod.midnight.network",
};

setNetworkId("preprod");

/** Races a promise against a timeout so a hanging SDK call fails loudly instead of silently. */
function withTimeout<T>(promise: Promise<T>, ms: number, label: string): Promise<T> {
  return Promise.race([
    promise,
    new Promise<never>((_, reject) => {
      const t = setTimeout(
        () => reject(new Error(`[timeout] ${label} did not resolve within ${ms / 1000}s`)),
        ms,
      );
      t.unref();
    }),
  ]);
}

function loadWalletSeed(): string {
  if (!existsSync(WALLET_SETUP_ENV_PATH)) {
    throw new Error(
      `Could not find ${WALLET_SETUP_ENV_PATH}. This script reads the funded wallet's seed ` +
        "from the sibling wallet-setup project (read-only) — make sure that project exists " +
        "and has already generated a wallet (WALLET_SEED in its .env).",
    );
  }
  const content = readFileSync(WALLET_SETUP_ENV_PATH, "utf8");
  const match = content.match(/^WALLET_SEED=(.+)$/m);
  if (!match || match[1].trim().length === 0) {
    throw new Error(`WALLET_SEED not found in ${WALLET_SETUP_ENV_PATH}.`);
  }
  return match[1].trim();
}

function deriveKeys(seedHex: string) {
  const hd = HDWallet.fromSeed(Buffer.from(seedHex, "hex"));
  if (hd.type !== "seedOk") {
    throw new Error("Invalid wallet seed");
  }
  const result = hd.hdWallet
    .selectAccount(0)
    .selectRoles([Roles.Zswap, Roles.NightExternal, Roles.Dust])
    .deriveKeysAt(0);
  hd.hdWallet.clear();
  if (result.type !== "keysDerived") {
    throw new Error(`Key derivation failed: ${result.type}`);
  }
  return result.keys;
}

/** See wallet-setup/src/index.ts for the detailed rationale on this readiness check. */
function isSubWalletReady(progress: {
  isConnected: boolean;
  appliedIndex: unknown;
  highestRelevantWalletIndex: unknown;
  isStrictlyComplete(): boolean;
}): boolean {
  if (typeof progress.appliedIndex !== "bigint" || typeof progress.highestRelevantWalletIndex !== "bigint") {
    return progress.isConnected === true;
  }
  try {
    return progress.isStrictlyComplete();
  } catch {
    return progress.isConnected === true;
  }
}

/** Waits for the unshielded sub-wallet to sync (does not wait on dust — see wallet-setup). */
async function connectUnshielded(wallet: WalletFacade, connectTimeoutMs: number) {
  return new Promise<Awaited<ReturnType<typeof wallet.waitForSyncedState>>>((resolve, reject) => {
    let connectTimer: NodeJS.Timeout | null = setTimeout(() => {
      sub.unsubscribe();
      reject(
        new Error(
          `[sync] Timed out after ${connectTimeoutMs / 1000}s: unshielded never reported isConnected=true.`,
        ),
      );
    }, connectTimeoutMs);

    const sub = wallet
      .state()
      .pipe(Rx.throttleTime(5_000, undefined, { leading: true, trailing: true }))
      .subscribe({
        next: (s) => {
          const u = s.unshielded.progress;
          const uReady = isSubWalletReady(u);
          console.log(`[sync] unshielded conn=${u.isConnected} ready=${uReady} ${u.appliedIndex}/${u.highestRelevantWalletIndex}`);
          if (connectTimer && u.isConnected) {
            clearTimeout(connectTimer);
            connectTimer = null;
          }
          if (uReady) {
            sub.unsubscribe();
            if (connectTimer) clearTimeout(connectTimer);
            resolve(s);
          }
        },
        error: (err) => {
          if (connectTimer) clearTimeout(connectTimer);
          reject(err);
        },
      });
  });
}

/**
 * Bridges a synced WalletFacade into the WalletProvider + MidnightProvider
 * shape midnight-js-contracts expects. Both interfaces are satisfied by the
 * same object — this is the standard pattern for Node.js scripts/CLIs
 * (there is no browser wallet-extension involved here).
 */
function createWalletProvider(
  facade: WalletFacade,
  shieldedSecretKeys: ledger.ZswapSecretKeys,
  dustSecretKey: ledger.DustSecretKey,
  state: Awaited<ReturnType<typeof connectUnshielded>>,
): WalletProvider & MidnightProvider {
  return {
    getCoinPublicKey: () => state.shielded.coinPublicKey.toHexString(),
    getEncryptionPublicKey: () => state.shielded.encryptionPublicKey.toHexString(),
    async balanceTx(tx, ttl) {
      const recipe = await facade.balanceUnboundTransaction(
        tx,
        { shieldedSecretKeys, dustSecretKey },
        { ttl: ttl ?? new Date(Date.now() + 30 * 60 * 1000) },
      );
      return await facade.finalizeRecipe(recipe);
    },
    submitTx: (tx) => facade.submitTransaction(tx),
  } as WalletProvider & MidnightProvider;
}

async function main() {
  console.log("=".repeat(70));
  console.log(`Deploying '${CONTRACT_NAME}' to Midnight Preprod`);
  console.log("=".repeat(70));

  const seedHex = loadWalletSeed();
  const keys = deriveKeys(seedHex);
  const networkId = getNetworkId();
  const unshieldedKeystore = createKeystore(keys[Roles.NightExternal], networkId);
  const unshieldedAddress = unshieldedKeystore.getBech32Address().toString();

  console.log(`Network:            ${networkId}`);
  console.log(`Unshielded address: ${unshieldedAddress}\n`);

  // Fail fast if the proof server isn't up — deployContract needs it.
  const health = await fetch(`${PROOF_SERVER_URL}/health`, { signal: AbortSignal.timeout(2000) }).catch(
    () => null,
  );
  if (!health || !health.ok) {
    throw new Error(
      `Proof server not detected at ${PROOF_SERVER_URL}/health. Start it first ` +
        "(`docker compose up -d` from the FairHire project root) and re-run.",
    );
  }
  console.log(`Proof server detected at ${PROOF_SERVER_URL}.\n`);

  const shieldedSecretKeys = ledger.ZswapSecretKeys.fromSeed(keys[Roles.Zswap]);
  const dustSecretKey = ledger.DustSecretKey.fromSeed(keys[Roles.Dust]);

  const configuration: DefaultConfiguration = {
    networkId,
    indexerClientConnection: {
      indexerHttpUrl: PREPROD.indexerHttpUrl,
      indexerWsUrl: PREPROD.indexerWsUrl,
    },
    relayURL: new URL(PREPROD.relayURL),
    provingServerUrl: new URL(PROOF_SERVER_URL),
    costParameters: { feeBlocksMargin: 5 },
    txHistoryStorage: new NoOpTransactionHistoryStorage(),
  };

  console.log("[init] Building WalletFacade...");
  const facade = await WalletFacade.init({
    configuration,
    shielded: (cfg) => ShieldedWallet(cfg).startWithSecretKeys(shieldedSecretKeys),
    unshielded: (cfg) => UnshieldedWallet(cfg).startWithPublicKey(PublicKey.fromKeyStore(unshieldedKeystore)),
    dust: (cfg) =>
      DustWallet(cfg).startWithSecretKey(dustSecretKey, ledger.LedgerParameters.initialParameters().dust),
  });
  console.log("[init] WalletFacade built. Starting sub-wallets...");
  await facade.start(shieldedSecretKeys, dustSecretKey);
  console.log("[init] Sub-wallets started.\n");

  try {
    console.log("[sync] Waiting for unshielded sync (connect timeout 60s; dust sync not awaited)...");
    const state = await connectUnshielded(facade, 60_000);
    console.log("[sync] unshielded ready.\n");

    const nightBalance = state.unshielded.balances[ledger.unshieldedToken().raw] ?? 0n;
    console.log(`[balance] tNIGHT balance: ${nightBalance}`);
    if (nightBalance === 0n && state.unshielded.availableCoins.length === 0) {
      throw new Error(
        `No tNIGHT at ${unshieldedAddress}. Fund it first (see wallet-setup project) and re-run.`,
      );
    }

    const walletProvider = createWalletProvider(facade, shieldedSecretKeys, dustSecretKey, state);

    if (!existsSync(PRIVATE_STATE_DIR)) {
      mkdirSync(PRIVATE_STATE_DIR, { recursive: true });
    }

    const zkConfigProvider = new NodeZkConfigProvider<"verifyAndApply">(CONTRACT_DIR);

    const providers = {
      privateStateProvider: levelPrivateStateProvider({
        privateStateStoreName: path.join(PRIVATE_STATE_DIR, `${CONTRACT_NAME}-private-state`),
        signingKeyStoreName: path.join(PRIVATE_STATE_DIR, `${CONTRACT_NAME}-signing-keys`),
        privateStoragePasswordProvider: () => "fairhire-deploy-script-local-only",
        accountId: unshieldedAddress,
      }),
      publicDataProvider: indexerPublicDataProvider(PREPROD.indexerHttpUrl, PREPROD.indexerWsUrl),
      zkConfigProvider,
      proofProvider: httpClientProofProvider(PROOF_SERVER_URL, zkConfigProvider),
      walletProvider,
      midnightProvider: walletProvider,
    };

    console.log("\n[deploy] Building CompiledContract binding...");
    const compiledContract = CompiledContract.make(CONTRACT_NAME, Contract).pipe(
      CompiledContract.withVacantWitnesses,
      CompiledContract.withCompiledFileAssets(CONTRACT_DIR),
    );

    console.log("[deploy] Submitting deployment transaction (this proves + balances + submits)...");
    const deployed = await withTimeout(
      deployContract(providers as never, {
        compiledContract,
        privateStateId: `${CONTRACT_NAME}PrivateState`,
        initialPrivateState: {},
      } as never),
      180_000,
      "deployContract",
    );

    const { contractAddress, txId, blockHeight } = deployed.deployTxData.public;
    console.log("\n" + "=".repeat(70));
    console.log("Deployment succeeded.");
    console.log(`  contractAddress: ${contractAddress}`);
    console.log(`  txId:            ${txId}`);
    console.log(`  blockHeight:     ${blockHeight}`);
    console.log("=".repeat(70));

    const existing = existsSync(DEPLOYED_CONTRACTS_PATH)
      ? (JSON.parse(readFileSync(DEPLOYED_CONTRACTS_PATH, "utf8")) as Record<string, unknown>)
      : {};
    const updated = {
      ...existing,
      [CONTRACT_NAME]: {
        address: contractAddress,
        network: "preprod",
        txId,
        blockHeight: typeof blockHeight === "bigint" ? blockHeight.toString() : blockHeight,
        deployerUnshieldedAddress: unshieldedAddress,
        deployedAt: new Date().toISOString(),
      },
    };
    writeFileSync(DEPLOYED_CONTRACTS_PATH, JSON.stringify(updated, null, 2) + "\n", "utf8");
    console.log(`\nWrote deployment metadata to ${DEPLOYED_CONTRACTS_PATH}`);
  } finally {
    await facade.stop();
  }
}

main()
  .catch((err) => {
    console.error("\nFatal error:", err);
    process.exitCode = 1;
  })
  .finally(() => {
    setTimeout(() => process.exit(process.exitCode ?? 0), 500).unref();
  });
